name: Issue Auto Reply Bot

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add welcome comment on new issue
        uses: actions/github-script@v7
        with:
          script: |
            const body = `Thank you for raising this issue! Our team will review it soon. 
            For more queries, discussions, or approval of requests, please join our Discord server: [Discord Link](https://discord.com/invite/Yn9g6KuWyA)`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
